# Should the plugin send bStats Metrics?
bstats-metrics: true

staffchat:
  # Supports PlaceholderAPI
  format: '&bStaffChat &f» %vault_prefix% &b%sender%: &f%message%'

  # Shortcuts allow you to quick type in Staffchat without commands
  # Type the shortcuts in front of your message and itl wil send the message in Staffchat
  shortcut:
    enabled: true
    shortcuts:
      - '?'
      - '!'

  # Sound when a message is sent | Spigot Only
  sound:
    enabled: true
    sound: 'ENTITY_ARROW_HIT_PLAYER'
    volume: 50

#
# | Wiki |
#
# • Bungeecord •
# Sound will not work if you are running the plugin on Bungeecord
# PlaceholderAPI Placeholders will not work if you are running the plugin on Bungeecord
# You can use %server% in the format to display server name
#
# • Spigot •
# You can use PlaceholderAPI and Sounds if you are running the plugin on Spigot